### ISSUE TITLE
DevEco Studio 增加了对 image 的校验

### ISSUE THREAD

**Issue by sionnx** [wsxyeah/HarmonySU#2]
报错截图
<img width="596" alt="image" src="https://github.com/user-attachments/assets/b8f391a0-59e6-46f2-9e73-1ada5d8a476f">

DevEco Studio 版本：
<img width="431" alt="image" src="https://github.com/user-attachments/assets/65ee04d1-a27c-4d08-8bb8-dc44a350ebc6">

虚拟机版本：
<img width="1312" alt="image" src="https://github.com/user-attachments/assets/8e602630-bf71-4b70-8481-25921a4f4156">

大佬遇到过吗

**Comment by silasol** [comment]
有机会hook一下 

<img width="982" alt="image" src="https://github.com/user-attachments/assets/1e6f612b-a273-495b-b944-c545f4cfd859">
